### ISSUE TITLE
tlog : optimize blockbuffer package

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#214]
It is the package which handle tlog block timeout.

CPU profiling result is bad, as reported at https://github.com/g8os/blockstor/pull/209#issuecomment-304745984

**Comment by GlenDC** [comment]
Will be really good if you can fix this today as well. As right now the performance really suffers. And for example when I try to  convert a ubuntu server image, it _always_ fails for me with the tlogStorage implementation, as it can never finish on time with all the flushing.

On master this doesn't fail for me, but that's only because there the deduped vdisk isn't strongly consistent. Meaning that it flushes the data to external storage, even though the tlog server is really not finished yet.

Fixing this issue should hopefully help a lot with making the tlog also work with big images. So when testing, make sure to also try really big images.

**Comment by iwanbk** [comment]
>  it always fails for me with the tlogStorage implementation, as it can never finish on time with all the flushing.

failed because of io timeout?

**Comment by iwanbk** [comment]
The profiling result is a bit weird, because the biggest cpu time was caused by `sync.Mutex.Unlock`.

I must wrote stupid code or the profiling result doesn't tell the reality.

**Comment by iwanbk** [comment]
After taking a deeper look at the profiling result and comparing it with profiling result of master branch (yeah, i know that master branch is not valid anymore, but it has some clue on it).

I concluded that this package is not the real culprit of the slowness. It might be part of the culprit, but not the primary/real issue.
Some intros:
- this package handles the timed out tlog message, resend it again if possible
- this package run as separate goroutine

My observations:
- in profiling result of `master` branch, this package is not appeared at all. While in `tlogstorage` branch, this package is the monster
- the internal data structure is not optimized for big number of buffer as i pointed out at (https://github.com/g8os/blockstor/issues/162#issuecomment-302596841), but my benchmark didn't impacted by this
- this package might become slow if there are big numbers of lost messages.
- if we take a look at profiling graph, the culprit is `mutex.Unlock`, seems weird
- `blockbuffer.(*entry).isTimeout` also take too much time, i guess it can only happen if there are too many tlogs in the buffer

So, i think the slowness is caused by too much lost messages/responses. But yeah, it also indicates that this package doesn't work well in this too much lost messages situation.

I'll check #209 and back to this issue again

**Comment by iwanbk** [comment]
Moving this work to 'roadmap' because this package  is not appeared at the profiling result.
It also doesn't impact the performance.
[nbd-new-with-blockbuf.pdf](https://github.com/g8os/blockstor/files/1047005/nbd-new-with-blockbuf.pdf)

compared with almost-disabled blockbuf
[nbd-new-without-blockbuf.pdf](https://github.com/g8os/blockstor/files/1047009/nbd-new-without-blockbuf.pdf)

**Comment by iwanbk** [comment]
Fixed by #262
