### ISSUE TITLE
nbdserver does hangup when sending sighub if there are no active clients

### ISSUE THREAD

**Issue by grimpy** [zero-os/0-Disk#243]
![170605_233250](https://cloud.githubusercontent.com/assets/143869/26805788/f589fc30-4a4d-11e7-8933-e51fae2cb1bb.png)
When sending a sighup signal to a nbdserver which is not handling active connections the nbdservers does a hangup see screenshot

However when doing a sighup when it is handling a connection it does a reload properly (atleast thats what I can tell from the logs at this point)

Please make sure that sighup never stops the nbdserver.

**Comment by GlenDC** [comment]
A real solution has been implemented in 415d8fb, in theory we could merge it into https://github.com/zero-os/0-Disk/tree/1.1.0-alpha-3, @robvanmieghem. However that branch already has a hack (787332a) since yesterday, which is non-invase and much safer. So for now I would keep that branch like it is. But at least in the master branch (and thus the alpha-4 release), there is a real solution available.
