### ISSUE TITLE
nbdserver : switch to ardb slave

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#276]
Part of #38

@GlenDC  How is the best way for the nbdserver to switch to ardb slave?
(assumed that slave is ready to be used)

I think nbdserver can simply re-create the redis pool, to point to the slave. (need to add config for this)

**Comment by GlenDC** [comment]
@iwanbk not sure actually. Normally when a server address has to switch, it gets done by the orchestrator, which overwrites the config file, and than triggers a SIGHUP.

I guess you could also do that, but than I wonder what would happen the next time the orchestrator updates the config, somehow we should also notify the orchestrator of this change no? It's a bit weird that this is being delegated to the tlogserver, I would have thought orchestrator is a better place for this?

**Comment by GlenDC** [comment]
The thing is, the tlogserver can't really overwrite the config file, as it's not on the same system as the nbdserver. The one which can do it, is the orchestrator, so I really think it has to go via that one. Personally I don't think this should have been the responsibility of the tlogserver, to me the tlogserver's only job is to manage aggregations and whatever that means.

**Comment by iwanbk** [comment]
tlogserver has no role at all in this switching process.

the flow:
- nbdserver detect that master is failing (can't connect, get/set failed, etc...)
- nbdserver send command to tlogserver to sync the slave (it is actually only waiting for  it to be fully synced)
- nbdserver switch to slave.

**Comment by GlenDC** [comment]
How the failing is detected?

And in case the nbdserver controls the switching from master to slave,
than there is no issue, as the nbdserver could choose to overwrite the config and send a SIGHUP signal.

I don't know how the entire system works together, but somehow the orchestrator needs to be also contacted to tell it about this change, no? Or how will it pick up this change? Because normally the (over)writing of the config and sending of SIGHUP signals is done by the orchestrator, so I'm a bit afraid that it would simply overwrite the config with the old master ardbs next time it updates.

**Comment by iwanbk** [comment]
> How the failing is detected?

If the ardb operation (connect, set, get) failed, and still failed after few reconnects, i think we can safely assume it as failed, no?

> I don't know how the entire system works together, but somehow the orchestrator needs to be also contacted to tell it about this change, no? 

Yeah, you're right. Just realized about it after i wrote my previous comment.
@robvanmieghem
