### ISSUE TITLE
Import / Export virtual machines

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-Disk#296]
We will use restic as a tool to export the VMs
Restic provide:
- deduplication
- encryption of the data
- incremental snapshots

Requirements:
- export:
  - disk need to be offline before it can be exported
  - 2 options for snapshot creation
    - hack restic so it can read our strorage cluster data. For that it would need to be able to read the metadata from a disk, then walk over all the blocks and save all the blocks as part of the same file.
    - restic supports stream as input, if we would have a tool that can stream the full content of a disk to stdout, we could pipe the two tools in order to create an exported version of the disk. E.g: `zeroctl export DISKID | restic --stdin --stdin-filename DISKID`
**Option 2 has been selected for implementation**

- import:
  -  mount the repo using the fuse of restic 
  - use a similar logic as the `zeroctl restore` command but instead of recreating a disk by replaying the tlog entries, it will recreate a disk by walking over the exported disk.

To be implemented:
Add 2 commands to the zeroctl command:
- export: takes a Vdisk ID as argument.
  - option: `--output filename` redirect the output into a file
  - option: `--output -` redirect the output to stdout so it can be pipe as a stream into restic.
          
- import: takes a file path as argument. The file is the exported version of the vdisk.

**Comment by GlenDC** [comment]
> restic supports stream as input, if we would have a tool that can stream the full content of a disk to stdout, we could pipe the two tools in order to create an exported version of the disk. E.g: zeroctl export DISKID | restic --stdin --stdin-filename DISKID
Option 2 has been selected for implementation

I'm going to assume that you mean `restic backup --stdin --stdin-filename DISKID`, as that is the only thing that makes sense if I compare your proposed command, with what I'm reading in the restic code base, which I have now available on my local work environment.

Sadly it seems that a lot of the functions used by the backup cmd is not exported, so it's going to be difficult to use the restic code as a library. I wonder why they did this, it's a shame, as we would otherwise have been able to call it directly from within our code.

So I think for now you're right, in that the only option for now seems to be having restic installed as a separate cmd, would that be ok for @grimpy  and this team, have you check this with them @zaibon?

In the meanwhile I'm going to see if I can open a conversation with the restic maintainers, to check about the reasons why there is no ready to use public Go API. Perhaps if there is no reason against it, we would cooperate together on this, to make it happen. I do think that spending time on this would only make sense if we are going to use restic for long, are we?

**Comment by GlenDC** [comment]
> In the meanwhile I'm going to see if I can open a conversation with the restic maintainers, to check about the reasons why there is no ready to use public Go API. Perhaps if there is no reason against it, we would cooperate together on this, to make it happen. I do think that spending time on this would only make sense if we are going to use restic for long, are we?

I opened an issue (restic/restic#1089) to ask a question about it, and the main guy behind the project seem pretty clear about the fact that there won't be an option to use restic as a Go Library, for a long time to come, if ever. Here is his response:

> At least for now, restic is meant to be a standalone binary, that's the use case we focus on. Exposing an API as a library (that is stable) with the same guarantees as we do for the restic CLI binary requires time and effort, which we do not have at the moment. The internal structures are changing a lot, so this would be even harder than it already is for the program.
> 
> We may reconsider this later when the internal structures have settled and we know that we can support this use case, but for now: I'm sorry, but restic is not a library, and the only interface we have is the binary.

So I think if we want to use restic, we'll have 2 options:

1. use it as a binary, and have users (0-orchestrator?) pipe our command with restic commands, as already proposed as a solution for this issue by @zaibon;
2. fork restic, and provide a Go API for the commands we care about, this would require maintenance work, which I think @zaibon didn't like, as it seems like restic is only a temporary solution, or am I wrong here?

**Comment by despiegk** [comment]
think we need to go for other solution

**Comment by GlenDC** [comment]
Closed in favor of the new approach proposed and discussed in #317.
