### ISSUE TITLE
complete & review docs/specs

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-Disk#308]
- see https://github.com/zero-os/0-Disk/tree/master/docs
- please make sure all content is up to date
- put more info in how the data formats are in ardb 
- more info about where metadata is
- create specs (which will be moved to docs once implemented) for export/import
- create specs (which will be moved to docs once implemented) for DR ideas

**Comment by despiegk** [comment]
questions to be answered
- how is metadata required for tlogbucket stored and where (which format)
- what happens if one of the ardb's is down when tlogbucket needs to be stored (so erasure coding cannot work)
- is all functionality as defined in tlog server readme implemented?
- whatever is not implemented should be moved to spec location on this repo

**Comment by GlenDC** [comment]
@despiegk what do you mean with DR ideas? Deduped Referencing? Data Redundancy?

**Comment by GlenDC** [comment]
> more info about where metadata is

This is about to change in milestone 7 though, was originally planned for milestone 6, but as your priorities changed, @zaibon shuffled them around. So should we document the current behavior, or can we already document the planned milestone 7 behavior?

**Comment by despiegk** [comment]
DR = Disaster Recovery (close enough to Data Redundancy (-:   )

**Comment by GlenDC** [comment]
@iwanbk can you help me out by going over the tlog module. Could you please improve the inline documentation of that module? Add any missing documentation, and update any outdated/poor documentation already there. You can add that in a commit to the open PR #318. Also feel free to do some minor improvements as part of that commit, in case you see something that could be very easily improved while reading through that code. Thanks!

**Comment by iwanbk** [comment]
> how is metadata required for tlogbucket stored and where (which format)

For the medatadata, tlogserver only store hashes of the last 5  aggregations.
It is stored as redis array.
We store it as array so in case of last hash failed to be decoded, we can still use previous hash.

This metadata stored on ALL of the DB instances to provide redundancy.

> what happens if one of the ardb's is down when tlogbucket needs to be stored (so erasure coding cannot work)

There is no handler right now, tlogserver will failed.

We can improve it by let it continue the operation as long as the number of failed server is no more than M (parity number) value. See #321

> is all functionality as defined in tlog server readme implemented?

Yes.
except this 

> We keep only backward links in our blockchain of history. We will add separate forward lining structure later in case it will be needed for the speed of recovery

Because we still don't have requirement for this.
It is doable.


> what is std size of tlogbucket

default aggregation size is 25 transactions. It can be easily changed from the config file.


I'm going to update the docs to reflect above answers

**Comment by iwanbk** [comment]
I have updated the tlogserver readme and inline docs

**Comment by GlenDC** [comment]
thanks @iwanbk!

The inline documentation is now up to date and improved in master (have merged PR #318, so that people can take this into account in their feature branches, as it covers the entire codebase, will open a new PR for the docs and specs themselves). So that should help with this issue, as inline documentation is in an OSS project just as important I would say as the external docs (/docs).

Next steps will be to update all READMEs, and also the /docs folder. Will also add an graph to show an overview of 0-Disk and how it all fits together (this is already worked on).

**Comment by GlenDC** [comment]
Great progress has been made. Most of the questions, and I think the more important questions, will be answered in the PR I'll make today, which will partly fix this issue. However:

+ documentation will be an ongoing process which we'll continue to push in quality and completeness in milestone 7, as we'll have a lot of new features by then;
+ right now the import/export feature (issue #317) is currently top priority, and certainly takes priority over the docs completion I would think;

Therefore I'll move this issue to milestone 7 (even though it will already be partly (if not mostly) completed. In between other work, I'l also keep working on pushing the quality and completeness of the docs, but right now it shouldn't be my main focus.

**Comment by GlenDC** [comment]
This is an issue that could remain open forever, as it is the type of work that will always be needed as features progress. So i'll just make a list here of things that have to still be done for now in respect to the issue creation, and once this list is resolved we can close this issue:

- [ ] Spec for the (deduped) reference counting (including the design/plans for the concurrent sweeper/scrubber);
- [ ] Spec for disaster recovery (can include information of what's already done, so that it can serve as a complete document that we later migrate to docs);
- [ ] Make sure README files of all services are up to date and link properly to the correct `/docs` documentation;
