### ISSUE TITLE
move specs/docs which are now in readme's to the docs folder

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-Disk#309]
- point the readme's to the docs folder in stead
- review all specs/docs (= issue #308)

**Comment by GlenDC** [comment]
> point the readme's to the docs folder in stead

At least for nbdserver, all existing docs already exist also in the docs folder AFAIK. @robvanmieghem do thinks its useful to also have at least some important knowledge available in the module's README, but that doc is usually also available in the docs folder. Is that OK? Or do you really want all the docs only available in the docs folder?

**Comment by GlenDC** [comment]
> point the readme's to the docs folder in stead

The 0-Disk consists of 3 sub-projects: NBDServer, TlogServer and zeroctl. All 3 have a README.md, as to provide some quick information. However, they _all_ point already to the docs folder (see the bottom of all those readme files). So not sure what this issue is about. Could you perhaps clarify, as I might be misunderstanding something here?

**Comment by despiegk** [comment]
Someone reading in docs folder should have all info or at least there need to be links from doc's folder intro docs to the readme's
my only goal is, it needs to be simple for people to find & read all information possible.

**Comment by GlenDC** [comment]
Will be resolved by improved docs issue #308.
