### ISSUE TITLE
tlog server should use 0-stor-lib (golang)

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-Disk#311]
suggestion
- remove ardb backend code for tlogserver
- use 0-stor-lib: see https://github.com/zero-os/0-stor-lib/blob/master/specs/principles.md

this has following benefits
- 1 single code path for all our storage needs
- etcd is redundant store for the metadata
- etcd can be store for double linked list

these components need to be changed to use 0-stor-lib:
- [x] flusher
- [x] slave sync (only the metadata) -> disabled in nbdserver now
- [x] tlog decoder
- [ ] manual end to end test 
- [ ] docs
- [ ] command line option

**Comment by GlenDC** [comment]
@despiegk can this be pushed to `1.1.0-alpha-7` please? The new team members are getting still up to date with the codebase. And it seems that the `0-stor-lib` and `0-stor` are still very far away from getting ready for usage. So I'm very skeptical that getting this ready and than also integrated in this codebase is realistic in the next 7 days.

Even having on this `1.1.0-alpha-7` is going to be rough, but at least it would buy as another week, which might still not be enough.

**Comment by iwanbk** [comment]
Once the `0-stor-lib` policy (described in https://github.com/zero-os/0-stor-lib/blob/master/specs/principles.md#pseudo-language-to-use-lib-example-in-python) it is pretty straightforward to move to 0-stor-lib from tlogserver point of view. It is because the metadata of tlog is pretty simple:
- tlog flusher : redis array of 5 last hashes.
- nbdserver's slave syncer : last synced sequence 

I added task list to the issue description

**Comment by iwanbk** [comment]
WIP can be found on `zerostor` branch

progress:
- all test passed, except the `test -race`
- `test -race` passed in `travis-testrace-tlog` branch. It split current `testrace` into three jobs:
     - nbd & config
     - tlogclient & stor package
     - tlogserver
  It is because the `testrace` just failed without any error or timeout message. After testing it in VM with small memory and CPU, i found that the test just `killed`, don't know the reason, still investigating

todo:
- merge solution in `travis-testrace-tlog` to `zerostor` branch
- documentation
- fix command line config (if needed)

**Comment by iwanbk** [comment]
Test race failed sometime on nbdserver's `TestBackendSigtermHandler`, more info and plan can be found at https://github.com/zero-os/0-Disk/issues/381#issuecomment-323253812
