### ISSUE TITLE
Import / Export virtual machines

### ISSUE THREAD

**Issue by despiegk** [zero-os/0-Disk#317]
supported backend
- ftp (optionally sftp)

definitions
- dedupe_map
    - capnp serialized list location/blake_hash
    - is done per 128 KB LBA block so 10,aabbccddeeffgghh is block 128 KB at LBA pos 128*10/4
    - 20GB data needs 3.5 MB of size in dedupe_map

export
- arguments: 
    - ftp url
    - encryption key
    - optional: blocksize (std 128 KB)
    - optional: which compression to use std lz4 
    - optional: name (if name not given then epoch)
- load dedupe_map
- walk over LBA storage space per 128 KB, check against dedupemap to see if changes
   - walk in parallel over the dedupe_map this allows fast comparison
- build in parallel the output dedupe_map
   - if not change, copy the original entry
   - if change write the new value
   - if new insert new value
- for each new found 128 KB block
   - compress block using [lz4](https://github.com/pierrec/lz4) or [xz](https://github.com/ulikunitz/xz)
   - encrypt the block with the encr key
   - add 4 byte CRC to end of file
   - upload block to $storagelocation/$aa/$bb/$ccddeeffgghh
   - at end upload the compressed/encr dedupe_map to $storagelocation/backups/$name

restore
- get dedupe_map
- ... to be completed

**Comment by despiegk** [comment]
remarks
- no restic
- there are golang libs for ftp access as well as for the compression algoritms
- need to read directly from the ardb's

**Comment by GlenDC** [comment]
Moved to milestone 7:

- Milestone 6 will be released tonight (0-Orchestrator skipped this milestone);
- 0-Orchestrator will anyhow only integrate and use this earliest in milestone 7, so no reason to delay the release of milestone 6 any longer;

**Comment by GlenDC** [comment]
Here is the stuff I use as you planned @despiegk:

+ for encryption/decryption I use AES256 in GCM;
+ for compression I use lz4, as the xz library is still a WIP (and lz4 is known for its speed);

However, for encoding (of the deduped map) I use [bencode][bencode] instead of Cap'n Proto. The reason being that serialization was both slow and not space-efficient using Cap'n Proto. For example when serializing a deduped map with 64k hashes (which takes `2,359,296` bytes in-memory):

+ With Cap'n Proto the full cycle takes 3.5+ seconds (`encode -> compress -> encrypt -> decrypt -> decompress -> decode`, on my laptop), and the final serialization size (encoded, compressed and encrypted) is: `4,258,212` bytes;
+ With [bencode][bencode] that same full cycle only takes ~0.7 seconds (`encode -> compress -> encrypt -> decrypt -> decompress -> decode`, on my laptop), and the final serialization size (encoded, compressed and encrypted) is: `2,667,457` bytes;

[bencode]: https://en.wikipedia.org/wiki/Bencode

**Comment by GlenDC** [comment]
Another difference with my implementation and the original proposal, I'm not adding the CRC to the end of file, as:
+ The CRC could be modified easily, so there is no real value in it;
+ If the file gets corrupt it is unlikely to be decrypted/decompressed correctly;
+ if it does managed to get decrypted AND decompressed correctly, despite being corrupted (which is not so likely I would think), there is already a checksum provided when using the LZ4 compression;
