### ISSUE TITLE
tlogserver : remove ResetFirstSequence feature

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#319]
It was added because nbdserver unable to get correct sequence number upon vdisk restart.
Once it has correct number, either by solving #273 or using `0-stor-lib`, we can remove this feature.

Correct way can be found on https://github.com/zero-os/0-Disk/issues/273#issuecomment-313401453

> modify the HandshakeResponse of the tlog handhsake protocol, so that it also returns the sequence it will use (it should be the firstSequence given by the client in case resetFirstSequence is true, but it can also be a higher value in case that bool is false), obviously we than also no longer want to reset that first sequence in our tlogStorage;
> in case the returned sequence of the server is higher than the one we had stored, you will need to use the tlog replay feature to get the vdisk up to date;
>

**Comment by GlenDC** [comment]
Depends on #311, and thus moved/planned this for milestone 7.

**Comment by iwanbk** [comment]
```
Depends on #311
```
It doesnt.

#311 is about tlog metadata, while this feature is about nbdserver metadata

**Comment by GlenDC** [comment]
It does depend on it, not because we are storing the metadata in a similar way, but because it's _the_ root issue that started the entire "integrate 0-stor-lib into 0-Disk" process.

So based on your description of this issue:

> using 0-stor-lib, we can remove this feature.

we resolve this once 0-stor-lib is implemented and used, so that we know what is what, and know for sure the best way to solve this.

In short it depends on it, because currently the scope and responsibilities are still in flux.

**Comment by iwanbk** [comment]
No, ResetFirstSequence is completely in-memory for tlogserver.

My complete description 
```
either by solving #273 or using 0-stor-lib
```
because #273 is about nbdserver, then 0-stor-lib here is also for nbdserver, not tlog.
