### ISSUE TITLE
`make testcodegen` failed but reported as passed on travis

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#343]
```
🍺  /usr/local/Cellar/capnp/0.6.1: 100 files, 9.9MB
6.11s$ make testcodegen
./scripts/codegeneration.sh
go: no such plugin (executable should be 'capnpc-go')
go: plugin failed: exit code 1
tlog/generate.go:3: running "capnp": exit status 1
The command "make testcodegen" exited with 0.
```

**Comment by GlenDC** [comment]
Thanks @iwanbk, great catch! It's because I'm trying to vendor all needed files from the go-capnp lib, so that you don't need to also download the lib yourself, as to avoid any version differences between the vendored lib and the one you (or travis) have in the $GOPATH src.

Somehow I must have forgotten to check the actual log, as it succeeded. Thanks for reporting.

How did you find out? Were you changing the schema or so? Or just by accident?

**Comment by iwanbk** [comment]
```
How did you find out? Were you changing the schema or so? Or just by accident?
```
just by accident

**Comment by GlenDC** [comment]
This issue has returned in master, since 6fdac6508eefc9f15b2bfbe672a0cc73d002c67a, which was a merged in a PR that was all about the test this issue relates to... How embarrassingly bad :(
