### ISSUE TITLE
travis osx build is slow

### ISSUE THREAD

**Issue by iwanbk** [zero-os/0-Disk#409]
I saw several times that we need to wait for more +- 20 seconds before the build started.
Need to move back to linux i think

**Comment by GlenDC** [comment]
Sure, I don't mind, it's slow because:

+ there are less MacOS machines available compared to Linux machines;
+ brew needs to update before we can update the tool;

However on Linux capnp seems to be out of date, at least the one we can download via apt-get. If it's up to date, I wouldn't mind, otherwise I think building from source doesn't make it much faster...

**Comment by GlenDC** [comment]
Considering OSX has had a lot of issues on travis lately, let's just switch back to Linux for now, even though we have to build from source as the trusty ubuntu Capnp package is 2 minor versions behind...
