### ISSUE TITLE
Need a way to check if a vdisk exists

### ISSUE THREAD

**Issue by FastGeert** [zero-os/0-Disk#502]
Currently it is only possible by listing up all the vdisks in the cluster.

Should be able to do something like:
```
zeroctl vdisk stat <<name>>
```

**Comment by GlenDC** [comment]
This functionality does already exist, it just isn't available yet as a zeroctl command.

Will expose it as a command as requested.

**Comment by FastGeert** [comment]
The reason for which I asked this feature, is to be able to harden the delete of a vdisk. Because now it crashes when we try to delete a non existing vdisk.

**Comment by GlenDC** [comment]
You seem to be on a roll to report bugs or missing features in a very indirect way.

> Because now it crashes when we try to delete a non existing vdisk.

If you mean that you are deleting vdisks `zeroctl delete vdisks vdiskid..` than that sounds more like a bug than anything else. I don't see why you are asking a new feature when really you are simply facing a bug either on 0-Disk site or the AYS site.

@FastGeert can you please be very detailed and explicit, while explaining what you exactly mean with your previous comment, because it confuses me a lot.

I just tested it and the `zeroctl delete vdisks vdiskid...` command is totally fine with deleting a non-existing vdisk (whether that is because it is not available on the storage servers or because it is not configured at all).

**Comment by FastGeert** [comment]
What is the exit code you get when trying to delete a non-existing vdisk ?

**Comment by GlenDC** [comment]
What is the exit code you get when trying to delete a non-existing vdisk 

`0`, for both the case that a vdisk simply has no (meta)data, as well as the fact that a vdisk is simply not configured. You do get error messages on the STDERR, but the exit code is `0` AFAIK.

**Comment by FastGeert** [comment]
Ok, then we don't need this.
