### ISSUE TITLE
snapshot with size x can't be imported as vdisk with size y, even though y >= x

### ISSUE THREAD

**Issue by khaledkbadr** [zero-os/0-Disk#607]
We have a `template:ubuntu-1604_default` snapshot in `ftp://hub.gig.tech` ftp server, which when running the `zeroctl describe` command returns a size of nearly 1.06 Gigabytes

```
zeroctl describe snapshot template:ubuntu-1604_default -s ftp://hub.gig.tech

{"snapshotID":"template:ubuntu-1604_default","blockSize":1048576,"size":1118830592,"version":"1.1.0"}
```
But when we do import that snapshot to a vdisk with a 2 Gib size (which is supposed to be larger than the size provided by the describe command) it returns an error `snapshot is too big for target vdisk`

**Vdisk static config**
```yml
img:vdisk:conf:static
================
blockSize: 4096
readOnly: true
size: 2
type: boot
```

**Import command**

```
zeroctl import vdisk img template:ubuntu-1604_default -j 100  --config 172.25.220.161:2379     --flush-size 128  --force   --storage ftp://hub.gig.tech
```

**Import command result/error**
```
RuntimeError:  
 -j, --jobs int                      the amount of parallel jobs to run (default 48)  
 -k, --key AESCryptoKey              an optional 32 byte fixed-size private key used for decryption when given   
 -s, --storage storageConfig         ftp server url or local dir path to import the backup from (default /.zero-os/nbd/vdisks)       
--tlog-priv-key string          32 bytes tlog private key (default "12345678901234567890123456789012")       
--tls-ca string                 optional PEM-encoded file containing the TLS CA Pool (defaults to system pool when not given)       
--tls-cert string               PEM-encoded file containing the TLS Client cert (FTPS will be used when given)       
--tls-insecure                  when given FTP over SSL will be used without cert verification       
--tls-key string                PEM-encoded file containing the private TLS client key       
--tls-server string       certs will be verified when given (required when --tls-insecure is not used)  
Global Flags:   
-v, --verbose   log available information  

snapshot is too big for target vdisk
```

**FYI:** it works if I increased the size of the vdisk to 3

**Comment by GlenDC** [comment]
It's because the reported size in `zeroctl describe` is not the real vdisk size. What it reports is the size of the data stored, purely in terms of blocks.

However blocks are spread once stored on a vdisk based on their block indices. So even if you have only 1.06 GiB in raw data, if you have even just one block that is stored outside the bounds of your 2GiB vdisk, it will not fit in your 2GiB vdisk.

It's because of this that if you make an export of a vdisk now that it also stores the relevant information of the source vdisk that was used to create that vdisk. So if you would run describe on a backup export made using zeroctl (commit https://github.com/zero-os/0-Disk/commit/8bd23fadaf2f25f4c3bc4d40a53c5b824915175a and later) you'll get the following information when you run describe:

```
$ zeroctl describe snapshot mybackup --pretty
{
  	"snapshotID": "mybackup",
  	"blockSize": 131072,
  	"size": 14024704,
  	"created": "2017-10-02T23:48:51-05:00",
  	"source": {
  	  	"vdiskID": "foo",
  	  	"blockSize": 4096,
  	  	"size": 10737418240
  	}
}
```
 
So it's much safer to base yourself on the size of the source vdisk. I'm fairly sure you should be using that size as as part of that vdisk data it probably stores somewhere in the OS data the disk size it think it has. If you put a smaller size than that one, wouldn't it try to write also in bigger areas at some point?

We could probably add another main property which would identify the max offset bound of the vdisk, which would give you an idea what the minimum size would be needed for a vdisk in order for `zeroctl import vdisk` not to complain. However, I'm not sure that would really be such a good idea, as because of what I described in my last paragraph.
